/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : pin_mux.c
**     Project     : TWR-K64F120M
**     Processor   : MK64FN1M0VMD12
**     Component   : PinSettings
**     Version     : Component 1.2.0, Driver 1.4, CPU db: 3.00.000
**     Repository  : KSDK 1.3.0
**     Compiler    : GNU C Compiler
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc.
**     All Rights Reserved.
**
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file pin_mux.c
** @version 1.4
** @brief
**
*/
/*!
**  @addtogroup pin_mux_module pin_mux module documentation
**  @{
*/

/* MODULE pin_mux. */

#include "fsl_device_registers.h"
#include "fsl_port_hal.h"
#include "fsl_sim_hal.h"
#include "pin_mux.h"


void configure_enet_pins(uint32_t instance)
{
	PORT_HAL_SetMuxMode(PORTA,7u,kPortMuxAlt5);			// RMII MDIO
	PORT_HAL_SetOpenDrainCmd(PORTA,7u,true);
	PORT_HAL_SetPullMode(PORTA,7u,kPortPullUp);
	PORT_HAL_SetPullCmd(PORTA,7u,true);

	PORT_HAL_SetMuxMode(PORTA,8u,kPortMuxAlt5);			// RMII MDDC
	/* Affects PORTA_PCR13 register */
	PORT_HAL_SetMuxMode(PORTA,13u,kPortMuxAlt4);		// RMII RxD0
	/* Affects PORTA_PCR12 register */
	PORT_HAL_SetMuxMode(PORTA,12u,kPortMuxAlt4);		// RMII RxD1
	/* Affects PORTA_PCR14 register */
	PORT_HAL_SetMuxMode(PORTA,14u,kPortMuxAlt4);		// RMII CRS DV
	/* Affects PORTA_PCR5 register */
	PORT_HAL_SetMuxMode(PORTA,5u,kPortMuxAlt4);			// RMII RX ER
	/* Affects PORTA_PCR16 register */
	PORT_HAL_SetMuxMode(PORTA,16u,kPortMuxAlt4);		// RMII TxD0
	/* Affects PORTA_PCR17 register */
	PORT_HAL_SetMuxMode(PORTA,17u,kPortMuxAlt4);		// RMII TxD1
	/* Affects PORTA_PCR15 register */
	PORT_HAL_SetMuxMode(PORTA,15u,kPortMuxAlt4);		// RMII TxEN
	/* Affects PORTA_PCR28 register */
	//PORT_HAL_SetMuxMode(PORTA,28u,kPortMuxAlt4);		// MII Tx ER
	PORT_HAL_SetMuxMode(PORTE,26u,kPortMuxAlt2);		// RMII TxEN
}


void configure_i2c_pins(uint32_t instance)
{
  switch(instance) {
    case I2C0_IDX:                       /* I2C0 */
//      PORT_HAL_SetMuxMode(PORTE,10u,kPortMuxAlt2);
//      PORT_HAL_SetOpenDrainCmd(PORTE,10u,true);
//      PORT_HAL_SetMuxMode(PORTE,11u,kPortMuxAlt2);
//      PORT_HAL_SetOpenDrainCmd(PORTE,11u,true);
      break;
    case I2C1_IDX:                       /* I2C1 */
      PORT_HAL_SetMuxMode(PORTC,10u,kPortMuxAlt2);
      PORT_HAL_SetOpenDrainCmd(PORTC,10u,true);
      PORT_HAL_SetMuxMode(PORTC,11u,kPortMuxAlt2);
      PORT_HAL_SetOpenDrainCmd(PORTC,11u,true);
      break;
    case I2C3_IDX:                       /* I2C0 */
      PORT_HAL_SetMuxMode(PORTE,10u,kPortMuxAlt2);
      PORT_HAL_SetOpenDrainCmd(PORTE,10u,true);
      PORT_HAL_SetMuxMode(PORTE,11u,kPortMuxAlt2);
      PORT_HAL_SetOpenDrainCmd(PORTE,11u,true);
      break;
    default:
      break;
  }
}


void configure_sdhc_pins(uint32_t instance)
{
	/* Affects PORTE_PCR3 register */
	PORT_HAL_SetMuxMode(PORTE,3u,kPortMuxAlt4);
	PORT_HAL_SetPullMode(PORTE,3u,kPortPullUp);
	PORT_HAL_SetPullCmd(PORTE,3u,true);
	PORT_HAL_SetDriveStrengthMode(PORTE,3u,kPortHighDriveStrength);

	/* Affects PORTE_PCR1 register */
	PORT_HAL_SetMuxMode(PORTE,1u,kPortMuxAlt4);
	PORT_HAL_SetPullMode(PORTE,1u,kPortPullUp);
	PORT_HAL_SetPullCmd(PORTE,1u,true);
	PORT_HAL_SetDriveStrengthMode(PORTE,1u,kPortHighDriveStrength);

	/* Affects PORTE_PCR0 register */
	PORT_HAL_SetMuxMode(PORTE,0u,kPortMuxAlt4);
	PORT_HAL_SetPullMode(PORTE,0u,kPortPullUp);
	PORT_HAL_SetPullCmd(PORTE,0u,true);
	PORT_HAL_SetDriveStrengthMode(PORTE,0u,kPortHighDriveStrength);

	/* Affects PORTE_PCR5 register */
	PORT_HAL_SetMuxMode(PORTE,5u,kPortMuxAlt4);
	PORT_HAL_SetPullMode(PORTE,5u,kPortPullUp);
	PORT_HAL_SetPullCmd(PORTE,5u,true);
	PORT_HAL_SetDriveStrengthMode(PORTE,5u,kPortHighDriveStrength);

	/* Affects PORTE_PCR4 register */
	PORT_HAL_SetMuxMode(PORTE,4u,kPortMuxAlt4);
	PORT_HAL_SetPullMode(PORTE,4u,kPortPullUp);
	PORT_HAL_SetPullCmd(PORTE,4u,true);
	PORT_HAL_SetDriveStrengthMode(PORTE,4u,kPortHighDriveStrength);

	/* Affects PORTE_PCR2 register */
	PORT_HAL_SetMuxMode(PORTE,2u,kPortMuxAlt4);
	PORT_HAL_SetPullMode(PORTE,2u,kPortPullUp);
	PORT_HAL_SetPullCmd(PORTE,2u,true);
	PORT_HAL_SetDriveStrengthMode(PORTE,2u,kPortHighDriveStrength);
}

// Connected TWR_MEM
void configure_sdcard_spi_pins(uint32_t instance)
{
	/* SPI2_CS1 */
	PORT_HAL_SetMuxMode(PORTD,15u,kPortMuxAlt2);
	PORT_HAL_SetPullMode(PORTD,15u,kPortPullUp);
	PORT_HAL_SetPullCmd(PORTD,15u,true);

	/* SPI2_SCK */
	PORT_HAL_SetMuxMode(PORTD,12u,kPortMuxAlt2);

	/* SPI2_SOUT */
	PORT_HAL_SetMuxMode(PORTD,13u,kPortMuxAlt2);
	PORT_HAL_SetPullMode(PORTD,13u,kPortPullUp);
	PORT_HAL_SetPullCmd(PORTD,16u,true);

	/* SPI2_SIN */
	PORT_HAL_SetMuxMode(PORTD,14u,kPortMuxAlt2);
	PORT_HAL_SetPullMode(PORTD,14u,kPortPullUp);
	PORT_HAL_SetPullCmd(PORTD,14u,true);

}

void configure_flash_spi_pins(uint32_t instance)
{
	/* SPI2_CS0 */
	PORT_HAL_SetMuxMode(PORTD,11u,kPortMuxAlt2);
	PORT_HAL_SetPullMode(PORTD,11u,kPortPullUp);
	PORT_HAL_SetPullCmd(PORTD,11u,true);

	/* SPI2_SCK */
	PORT_HAL_SetMuxMode(PORTD,12u,kPortMuxAlt2);

	/* SPI2_SOUT */
	PORT_HAL_SetMuxMode(PORTD,13u,kPortMuxAlt2);
	PORT_HAL_SetPullMode(PORTD,13u,kPortPullUp);
	PORT_HAL_SetPullCmd(PORTD,16u,true);

	/* SPI2_SIN */
	PORT_HAL_SetMuxMode(PORTD,14u,kPortMuxAlt2);
	PORT_HAL_SetPullMode(PORTD,14u,kPortPullUp);
	PORT_HAL_SetPullCmd(PORTD,14u,true);

}

void configure_uart_pins(uint32_t instance)
{
  switch(instance) {

	case UART0_IDX: //<> // SIM
		PORT_HAL_SetMuxMode(PORTA,1u,kPortMuxAlt2);		// RxD
		PORT_HAL_SetMuxMode(PORTA,2u,kPortMuxAlt2); 	// TxD

	break;

	case UART1_IDX: //<> // MB
		PORT_HAL_SetMuxMode(PORTC,3u,kPortMuxAlt3);		// RxD
		PORT_HAL_SetMuxMode(PORTC,4u,kPortMuxAlt3);		// TxD
	break;

	case UART2_IDX: //<>  // AI
		PORT_HAL_SetMuxMode(PORTD,2u,kPortMuxAlt3);		// RxD
		//PORT_HAL_SetMuxMode(PORTD,3u,kPortMuxAlt3);		// TxD
	break;

	case UART3_IDX: //<>  // PC
		PORT_HAL_SetMuxMode(PORTB,10u,kPortMuxAlt3);	// RxD
		PORT_HAL_SetMuxMode(PORTB,11u,kPortMuxAlt3);	// TxD
	break;

	case UART4_IDX: //<> // UI
		PORT_HAL_SetMuxMode(PORTE,24u,kPortMuxAlt3);	// TxD
		PORT_HAL_SetMuxMode(PORTE,25u,kPortMuxAlt3);	// RxD
	break;

	case 5:		// DBG
		PORT_HAL_SetMuxMode(PORTD,9u,kPortMuxAlt5);		//
		PORT_HAL_SetMuxMode(PORTD,8u,kPortMuxAlt5);		//
		//SIM_HAL_SetLpuartTxSrcMode(SIM, 0, kSimLpuartTxsrcPin);
		//SIM_HAL_SetLpuartRxSrcMode(SIM, 0, kSimLpuartRxsrcPin);

	break;

    default:
      break;
  }
}




/* END pin_mux. */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
